controllers:
    resource: ../src/Controller/
    type: attribute
_index:
    path: /{path}
    controller: App\Controller\HomeController::index
_index2:
    path: /{path}/{path2}
    controller: App\Controller\HomeController::index
_index3:
    path: /{path}/{path2}/{path3}
    controller: App\Controller\HomeController::index
_index4:
    path: /{path}/{path2}/{path3}/{path4}
    controller: App\Controller\HomeController::index